### ISSUE TITLE
Missing dependency on url package

### ISSUE THREAD

**Issue by sshymko** [juji/cookie-manager#1]
The library relies on the NPM package `url` that may be missing in some environments, such as React Native.

Declaring the dependency in `package.json` fixes the problem:
```js
{
  "dependencies": {
    "url": "^0.11.0"
  }
}
```

**Comment by juji** [comment]
Thanks.. fixed..

**Comment by sshymko** [comment]
Thanks @juji! Looking forward to use it as soon as the new NPM version is published.
